### ISSUE TITLE
Problems with search function

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe-old#1067]
The search bar doesn't seem to work very well, in two ways. 

(1) **Not finding topics.** 
For example, when I type in "marketing 2022" it doesn't find any of my topics that have both these words in, e.g. below. 

_Becca - Anett Marketing meetings 2022
COS Marketing roles plan for 2022
Marketing Meetings 2022_

![image](https://user-images.githubusercontent.com/61320526/180972137-3577d4f7-995d-429f-80d7-43fb1af022e7.png)

If I just type in "Marketing" however, it does show up these, but also all the other topics with the word "marketing" in.

(2) **Weird UX behaviour.** 
If you type in the search term and press enter, the search function just refreshes whatever page you were on, i.e. nothing happens, and what you have already typed in the search bar disappears. Gets me every time! As it seems that you are meant to just type it in and wait for it to load, but seeing as the loading is always a second or two slower than the typing, I always press enter to "submit" the search.

**Comment by anettlinno** [comment]
Triage 77. Replicated issues. "View more" is not working correctly and topics that I have created did not come up with search.
Search brought up old topics but should show the newest ones.

Sending to investigation. Est. investigation time 1 hour.

**Comment by ilmartyrk** [comment]
View more fixed with [angular update](https://github.com/citizenos/citizenos-fe-old/issues/1005)

**Comment by BeccaMelhuish** [comment]
@ilmartyrk @anettlinno Still not working for me by the way...

This is what happens when I type in "marketing 2022" without pressing enter: 

![image](https://user-images.githubusercontent.com/61320526/227215675-41f01be8-4152-4b7f-9fdb-d09b248e0af9.png)

And then when I press enter, even more confusingly my search term just disappears keeping the blank results open:

![image](https://user-images.githubusercontent.com/61320526/227215935-dd92b03f-be15-4a8f-af92-c5047749ab74.png)

It doesn't even say "no search results", just blankness...

**Comment by BeccaMelhuish** [comment]
P.S. In between typing in each of the characters 2022, e.g. here between typing 202 and 2022, the "oops no search results" message flashes up for half a second (too quick to catch it in the screenshot), then vanishes again, repeatedly until I finish typing and it stays blank... Definitely something quite off!  

![image](https://user-images.githubusercontent.com/61320526/227216558-a1536a66-26e4-4747-bdc5-3bf9298e6e9d.png)

**Comment by BeccaMelhuish** [comment]
Also maybe this should be a new issue, but "Context" search results is a bit of an odd way to say it (removing the "context" would be better) and there's spaces missing where highlighted here: 

![image](https://user-images.githubusercontent.com/61320526/227216934-afc85f72-91ff-43dc-b42b-26d41efd09dc.png)

**Comment by BeccaMelhuish** [comment]
Also, as per the results above, when it does come back with the results it's showing older ones first. Should be newest (most recently active, and therefore most relevant ones) at the top surely? :)

**Comment by BeccaMelhuish** [comment]
A thought: maybe some QA testing from Sara (when she has time) is needed on the search feature? Seeing as it's such an important one :)

**Comment by ilmartyrk** [comment]
Better to make a list of items to fix @BeccaMelhuish add to here:
- [ ] Display no results text if no results found
- [ ] Result list heading text formatting issues (no space)
- [ ] Order results by newer first
- [ ] Remove word "Context" from result list headings
- [ ] Make it so there is no difference between whether a user presses enter after search term or not
- [ ] Make sure search function is finding topics with all search words included, not necessarily next to each other

**Comment by BeccaMelhuish** [comment]
Great thanks @ilmartyrk, have added to your list! 

Just to explain the last two further:

- "Make it so there is no difference between whether a user presses enter after search term or not".
I find this to be a UX issue as if a user is used to typing a search word and pressing enter they will do so (especially if the results are loading slowly and didn't pop up during typing). But doing so currently seems to stop the search from working and they just get a blank search page (confusing and seems like the search is broken), or if some results have loaded it seems to open the top result (if I'm not mistaken?) which is also very confusing. 

- Make sure search function is finding topics with all search words included, not necessarily next to each other
This one is to do with the fact that searching for Marketing 2022 didn't bring any results even though I have lots with those two words in them. I guess the search function is treating it as though it is "Marketing 2022" in inverted commas (on a Google search) - so as if the two words need to be next to each other. So to summarise, in my opinion if someone types more than one word, the search should bring up topics with those words in anywhere in the title, not necessarily next to each other and in that order :)

**Comment by ilmartyrk** [comment]
Moving this issue to https://github.com/citizenos/citizenos-fe/issues/36
